import numpy as np
import pytest

from alphago.games.connect_four import (
    ConnectFour,
    action_list_to_state,
    optimal_moves,
)


def test_connect_four_initial_state(mocker):
    mock = mocker.MagicMock()
    ConnectFour.__init__(mock)

    assert np.shape(mock.initial_state) == (42,)
    assert ~np.any(mock.initial_state)


def test_compute_next_states_on_full_column(mocker):
    # Full first column
    state = tuple(1 if i % 7 == 0 else 0 for i in range(42))

    expected_next_actions = list(range(1, 7))
    mock = mocker.MagicMock()
    computed = ConnectFour.legal_actions(mock, state)
    assert expected_next_actions == list(computed.keys())


NEXT_STATES_STATES = [
    (
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        1,
        -1,
        0,
        1,
        0,
        0,
    )
]


NEXT_NEXT_STATES_STATES = [
    {
        0: (
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            -1,
            0,
            0,
            1,
            1,
            -1,
            0,
            1,
            0,
            0,
        ),
        1: (
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            -1,
            0,
            0,
            0,
            1,
            -1,
            0,
            1,
            0,
            0,
        ),
        2: (
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            -1,
            0,
            0,
            0,
            1,
            -1,
            0,
            1,
            0,
            0,
        ),
        3: (
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            -1,
            0,
            0,
            0,
            1,
            -1,
            1,
            1,
            0,
            0,
        ),
        4: (
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            -1,
            0,
            0,
            0,
            1,
            -1,
            0,
            1,
            0,
            0,
        ),
        5: (
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            -1,
            0,
            0,
            0,
            1,
            -1,
            0,
            1,
            1,
            0,
        ),
        6: (
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            -1,
            0,
            0,
            0,
            1,
            -1,
            0,
            1,
            0,
            1,
        ),
    }
]


@pytest.mark.parametrize(
    "state, expected_next_states",
    zip(NEXT_STATES_STATES, NEXT_NEXT_STATES_STATES, strict=False),
)
def test_compute_next_states(state, expected_next_states, mocker):
    cf = ConnectFour()
    next_states = cf.legal_actions(state)
    assert next_states == expected_next_states


@pytest.mark.parametrize("column", range(7))
def test_action_list_to_state_matches_legal_actions_oracle(column):
    """action_list_to_state([c]) equals the engine's own next state.

    Self-consistency oracle: applying column ``c`` from the
    initial state via ``legal_actions`` produces the ground-truth state, so no
    hand-computed expected value is needed. Player 1 moves first and
    ``legal_actions`` places the marker ``1``, so the single-move state built by
    ``action_list_to_state`` must place ``+1`` in the same cell. This pins the
    symbol-mapping fix and fails against the pre-fix inverted mapping.
    """
    cf = ConnectFour()
    oracle_next_state = cf.legal_actions(cf.initial_state)[column]
    assert action_list_to_state([column]) == oracle_next_state


SUB_GRIDS = [(1, 1, 0, 0, 0, 1, -1, 0, 0, 1, 0, 1, 1, 0, 0, 1), (0,) * 16]

EXPECTED_LINE_SUMS = [[2, 0, 2, 2, 2, 3, -1, 2, 3, 1], [0 for i in range(10)]]


@pytest.mark.parametrize(
    "grid, expected_line_sums", zip(SUB_GRIDS, EXPECTED_LINE_SUMS, strict=False)
)
def test_connect_four_line_sums_4_by_4(grid, expected_line_sums, mocker):
    line_sums = ConnectFour._calculate_line_sums_4_by_4(grid)
    assert np.all(line_sums == expected_line_sums)


TERMINAL_STATES = [
    (1,) * 42,  # All 1s
    (-1,) * 42,  # All -1s
    tuple((-1) ** i for i in range(42)),  # Alternating checkerboard
    (
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ),
    (
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ),
    (
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
    ),
]


@pytest.mark.parametrize("state", TERMINAL_STATES)
def test_is_terminal_returns_true_for_terminal_states(state, mocker):
    cf = ConnectFour()
    assert cf.is_terminal(state)


UTILITY_STATES = [
    (
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ),
    (
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ),
    (
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
    ),
]

EXPECTED_UTILITIES = [{1: 1, 2: -1}, {1: -1, 2: 1}, {1: 1, 2: -1}]


@pytest.mark.parametrize(
    "state, expected_utility", zip(UTILITY_STATES, EXPECTED_UTILITIES, strict=False)
)
def test_utility(state, expected_utility, mocker):
    cf = ConnectFour()
    assert cf.utility(state) == expected_utility


STATES = [
    (
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        -1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
    )
]

div = "---+---+---+---+---+---+---"
# additional newline character accounts for the one added to the output
# by the print function itself
OUTPUTS = [
    "\n".join(
        (
            " o |   |   |   |   |   |   ",
            div,
            "   | o |   |   |   |   | x ",
            div,
            "   |   | o |   |   |   |   ",
            div,
            " x |   |   | o |   |   |   ",
            div,
            "   |   |   |   |   |   |   ",
            div,
            "   |   |   |   |   | x |   ",
        )
    )
    + "\n",
]


@pytest.mark.parametrize("state, expected_output", zip(STATES, OUTPUTS, strict=False))
def test_display_function_outputs_correct_strings(state, expected_output, capsys):
    ConnectFour.display(state)
    output = capsys.readouterr().out
    assert output == expected_output


def test_optimal_moves_rejects_non_digit_input(mocker):
    # Stub the native solver so the binary is never executed; validation must
    # reject the non-digit move string before subprocess.run is ever reached.
    mock_run = mocker.patch("alphago.games.connect_four.subprocess.run")
    mock_run.return_value = mocker.MagicMock(stdout=b"4x 0 1")

    with pytest.raises(ValueError, match="'4x'"):
        optimal_moves([4, "x"])

    mock_run.assert_not_called()
